apiVersion: v1
kind: Namespace
metadata:
  name: ocp-ai
  labels:
    app.kubernetes.io/part-of: coder-aigov-demo
    app.kubernetes.io/component: inference
  annotations:
    description: "Namespace for Red Hat AI Inference Server (RHAIIS) and related sovereign-inference components."
