#!/usr/bin/env bash
# Regenerate manifests/coder-agents-config/configmap.yaml from the
# canonical script at scripts/coder-agents-provider-model-config.sh.
#
# The Argo CD-managed Job (manifests/coder-agents-config/job.yaml)
# mounts the rendered ConfigMap and runs the script. Because Argo CD
# uses plain-directory mode (no kustomize) for our manifest paths, the
# ConfigMap has to be checked into git — kustomize's `configMapGenerator`
# would require enabling `--load-restrictor=LoadRestrictionsNone` cluster-
# wide on the ArgoCD CR, which we don't want to touch for one Job.
#
# Run this any time you edit coder-agents-provider-model-config.sh, then
# commit both files together.
#
# Usage:
#   ./scripts/render-coder-agents-configmap.sh
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPT="${REPO_ROOT}/scripts/coder-agents-provider-model-config.sh"
OUT="${REPO_ROOT}/manifests/coder-agents-config/configmap.yaml"

[ -f "$SCRIPT" ] || { echo "ERROR: $SCRIPT not found" >&2; exit 1; }
mkdir -p "$(dirname "$OUT")"

{
  cat <<'YAML'
# GENERATED BY scripts/render-coder-agents-configmap.sh — DO NOT EDIT BY HAND.
#
# Source of truth: scripts/coder-agents-provider-model-config.sh
# After editing the script, run:
#   ./scripts/render-coder-agents-configmap.sh
# and commit the regenerated configmap.yaml in the same change.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coder-agents-config-script
  namespace: coder
  labels:
    app.kubernetes.io/name: coder-agents-config
    app.kubernetes.io/part-of: coder-aigov-demo
data:
  coder-agents-provider-model-config.sh: |
YAML
  # Indent every script line by 4 spaces so it parses as the value of
  # the YAML literal block scalar above.
  sed 's/^/    /' "$SCRIPT"
} > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT") lines)."
