#!/usr/bin/env bash
# Regenerate manifests/coder-agents-config/configmap.yaml from the
# canonical script at scripts/coder-agents-provider-model-config.sh.
#
# The Argo CD-managed Job (manifests/coder-agents-config/job.yaml)
# mounts the rendered ConfigMap and runs the script. Because Argo CD
# uses plain-directory mode (no kustomize) for our manifest paths, the
# ConfigMap has to be checked into git — kustomize's `configMapGenerator`
# would require enabling `--load-restrictor=LoadRestrictionsNone` cluster-
# wide on the ArgoCD CR, which we don't want to touch for one Job.
#
# Run this any time you edit coder-agents-provider-model-config.sh, then
# commit both files together.
#
# Usage:
#   ./scripts/render-coder-agents-configmap.sh
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPT="${REPO_ROOT}/scripts/coder-agents-provider-model-config.sh"
SYSTEM_PROMPT="${REPO_ROOT}/manifests/coder-agents-config/system-prompt.md"
PLAN_MODE="${REPO_ROOT}/manifests/coder-agents-config/plan-mode-instructions.md"
OUT="${REPO_ROOT}/manifests/coder-agents-config/configmap.yaml"

[ -f "$SCRIPT" ] || { echo "ERROR: $SCRIPT not found" >&2; exit 1; }
[ -f "$SYSTEM_PROMPT" ] || { echo "ERROR: $SYSTEM_PROMPT not found" >&2; exit 1; }
[ -f "$PLAN_MODE" ] || { echo "ERROR: $PLAN_MODE not found" >&2; exit 1; }
mkdir -p "$(dirname "$OUT")"

{
  cat <<'YAML'
# GENERATED BY scripts/render-coder-agents-configmap.sh — DO NOT EDIT BY HAND.
#
# Source of truth:
#   scripts/coder-agents-provider-model-config.sh (the bootstrap script)
#   manifests/coder-agents-config/system-prompt.md (Coder Agents system prompt appendix)
#   manifests/coder-agents-config/plan-mode-instructions.md (Coder Agents plan-mode instructions)
#
# After editing any of those source files, run:
#   ./scripts/render-coder-agents-configmap.sh
# and commit the regenerated configmap.yaml in the same change.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coder-agents-config-script
  namespace: coder
  labels:
    app.kubernetes.io/name: coder-agents-config
    app.kubernetes.io/part-of: coder-aigov-demo
data:
  coder-agents-provider-model-config.sh: |
YAML
  # Indent every script line by 4 spaces so it parses as the value of
  # the YAML literal block scalar above.
  sed 's/^/    /' "$SCRIPT"

  cat <<'YAML'
  system-prompt.md: |
YAML
  sed 's/^/    /' "$SYSTEM_PROMPT"

  cat <<'YAML'
  plan-mode-instructions.md: |
YAML
  sed 's/^/    /' "$PLAN_MODE"
} > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT") lines)."
