---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bridge-webhook-secret
  namespace: coder
spec:
  encryptedData:
    token: AgCfZkqOyvlWM98wPsCWZ6/F4uaP4LgvP1qdPnVrMMjcdM2GHrZv5vW/E/KAhdRq4bt9cbFiKea2Blv24Vjm6DLEzZUi8qahRla6ullh8HS/7o9uGyBiygIYX/lc8dceOVgASKCLCyAQ2cNTjX2Jh5LBlJnylTUhU8GtjczynoqK96ded66lvTNxc09E3r9aE8cbiXuVVcIAP+ZSZ98OS8Qg7+4FABHFZRzRTQ6s7M/MH1R1NblBUqWLhuABHg7HC3yERx0vmUJ7lJRvPnMq02m06YRVyhwpb5ZpXSKsNb2zj0tPo/xqmI+spJQqRyKeQpv60i1RMqjkrpTceVE6pOy4K8K6m7jgcGgS4oE7amK58dojKksMohpY2oNyAgqH73WAcAe93S7p9iMl99pVI4V7AnB5oXEPN0Y9XbLrq+2LVI3ehVNH4ZjZxtsmzJ+KVhZ2fWROJRymNegEAFQIaXLIlNDfb4qh8jIZFKABMjuEeXW3qwEZPyKAn+k1tP/4PZndt2IzHUTw0s0CJGrmvLlPvswoPyxZh97EpuIQpPU5LnJSJ+duDQFQnozvzaLEiVkcCQKEkKnV7r4d3Up7QCpkswVnPC+A0S4lzSBI7Hia5wvB7cv8H3x0GgxeJbvq7UbuH7Q36Dgsv2gd5MAu7FEKazXuJGLKsOF2FZ6rGf6yhji7tkJv1l3JbDE08q30UvJwhRzA3G1JzY/byqlz3RVfe7+xwjka0H4Jntx13Z6ihHr69Mvz3QKzaJz69D28cRSf00Jh5MsXG6volE+bAGAg
  template:
    metadata:
      name: bridge-webhook-secret
      namespace: coder
