---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: coder-provisioner-key
  namespace: coder
spec:
  encryptedData:
    key: AgBBJbl3nCGhIEQNPAtYbx9miV4eLZV8+DqK6TBOOtJ6xIbPV2BSvyfDR3Z1jGtM1zpPs6Ct6nuG04WOHecx1/R9uOwAfMkKtLQPK6Sjh1YiVxQluaTF/7428mSTUiH+z8r9oqkXoff14leJGsdyLNtHZ+jZssPvEAU5r7tggJ3J7BYU6gis6ZHvRGXDcmNEkIWzrQdXGfLue+6lYdBoC7/a74Vb9zQhfy/ORy2dmrU62eNxi2GhfU3eNC0TWMiMXXNJUxqGDOXB8ZpKiEJGdxKMH03aJBOc4+MVK81pHCCZQHYSU1KkSrDDvafldAkX6aC86uxfxpa4hap21NaOEDCsuVrkefoC/RSU9fGXj3HX4NSqnZjP3pTR4clMKuEwgPGzpai2jYqilGeroMgsSXNEX6HEiHRUDmB24BW/Sz5DHN1T6/cfwE2lpkOrbaoGf5JnSv5lT5uwNmb0tEWUwBKNATp/VdjvTBQERYnVJdUbltpdX09oc7irL30yVM65yxq91c6UNeWhhWx3th/COswBKU9QjKGtwMuviP1fV/9N6BWk5ZjeFdSjhvGVGWI/JzEM1W2f+GJjcM287Q3gudoux38djPKZfTHFvtwZIifph264wWYSp2jhVnUu3h79YWywoCE2q/6jWnkEX3rlvn0XtwdNCOc+UUU9YAZCJ5qkbJvUINRiV7lWUgqc1m4X2BtANqyZXe6u7GHkHYC3a64zuoWASKu3ZJ+MjFI0k7RG0ve2YmPXZ/RmWWyj
  template:
    metadata:
      name: coder-provisioner-key
      namespace: coder
