---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: coder-secrets
  namespace: coder
spec:
  encryptedData:
    github-client-id: AgBUXQ7sp+ZZQQbXnhOMNi3MYrfWJADWppgf8PBCBxT0+6absfLPHG819D9aI5aaG8n06rRe8lv1qTRFF6seib7RgsWodAEY4ZFsCohnjf1pK6JvUFgS2B7ODlB65tOkvbj7nlIOy51kfylss8PRNexp6hbEYjYVqy+hW1H3H+HBrTpRWRNx9Lt4Q9xsMybkzNnCHs01CbXH2BgDPQrmBTktHJUVnS+Z8t2Gzkkf7fIlPX6YX91JBjOjE6AEJCTaJ5h9E6BsJJTb0+keIR/2GFMOMo+GCMpvC0sPU8NS4QyYLhcItjZ5ftRwR8t37ILZ3Br8f451YxL+729vU0JLGCV4E3xJz9myzt2ygOiChYM9uqm0PfmiYD8CBaMZk2XJ9tZnVIN6DRnsNWFSyMbKtKx1pio5ku8CVRHbEn6GwVPVhVahxvhTzBVUdb2AHAxKemZ/956SczgSrZ+mx3oYwA77T28H+f2rHB7itUdYj1Slv7Iurz/jhH7q8umiVL1J2QeMjGLG3y4ZDV+gb26g3tFd6YYgRJ8wJC3JlLFDPDKdHhkGjEGIKnLmQU2wWLe4RztJ668NDJIbrNwzW86MExG0vxMSsRNEtqolKg2xR4+s7T03lAFU31z7mcNX3xA9jveVxR6u9sjIZEF5pzaRJzlvdNNk9AVmGg/YHx1k8Wq/RvjVl4ovsYvwXnwQAJN3pAdXQE5yaGMsWlOWADPoXdJs0WYUzw==
    github-client-secret: AgCfe4CjZbICl1rrfTXel3JJgqpGRyqNi44VemKA1XNz8RwHRaREYTZPoe/qKYdtUM8k4+Nk+6M10lsVj2flJgRmnQ7kNwy+KIkdUA/1YPfgNTXjZMkHqqRmy8DZAhP3159DLEoKLDAA1B43TITw8K4bw7lPSVPhBRIHbIfQEclMu5Vt42tIgna4aLM/PzS2iihLoa58NNGOtfpOocSSs43dFvIUnNY2cKlX1k+Uru78/BCXXo6MDGkV+jgqfgB/3qY4Lr/+PM+O0Gm/wKlGnjpPB8Y+TUN3wOyGi55WndXQP6i4b024OkHolo0rSbxTQ8n7J2cibI4tGhORrPGXjoED0J9TIzDTi7s4mlV3GKg9vJBeR3aavgt/rW8NxOY/GR1knXofLaZ9JIq/ADehyFrTwQeZnpqdYs5ANgTJzLNUj3KoN0kyeO2Q4P4FmAUWzhMIBgyDA6BS5y9hOQ5s1fBcXTQLC3ggSwlUAGAj/EdPcP6dypHkbOVmHXAPCFlRrn2gMrf9eBwmGLeqVy7GYzIzRh7Dx1qud5fZuyl1GPUFmZZSCqhD7JY8Y0ld8Wiu1re7M+5maYCXnPZNgcCU17QjTQSUo7DCUzYK6ET2nkN+JJrfn3heJ9s/9uyEsz7gOroCtzS7rhaII45DBYOsgKUJi0uvZRF4S/uWVKSAJL2rHvhLQvYRNymfv7rNDZxs/NfKX/UduTJJW578XRIuuXgC0acy9O8OHl+6ZindCO8xzhkLRMaicKMI
  template:
    metadata:
      name: coder-secrets
      namespace: coder
