---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: coder-admin-token
  namespace: coder
spec:
  encryptedData:
    token: AgAaXZH72g/NuOtMlfb6hhDcZmWkOd0qUmbv2QXlLR/gq1B2KZGYOTQd4xR+MBWAed2TDgvFoE4RjZ7DrSzWvS6gOpXfIzUjSUgC4xd9X96lB9SOps5S6nhDUzz5/0BP4PScRBeOX9RrlTseWy0Sfoda0IPaP2sx8i7Z81srLgaDq4Rp7r3Dvh7KIrIJ6YGwTMkB/dyZrj7ZjN+RplbQadR8y2txLeN5pSGjT1AJl6564L8pjTIub1npdoadnmb5Lb955t406Eqhhhv4MrbS8aBHrXH3W3nOEjtxEibTZ6RRiWGJDhUfYfkFxutyFKnA+3gy47aqBO4LJ1h00qduIoIbUTiVY+5WSI84ir2BEeglqpPZXoIMBIveUWlGtXNA4/nwMi1OmiZ3HvP6EwevlfTNWqUdYFFtKnGJMkqu8ZI4Tq8tjwOGLQpDcdQ3ssO6llmcBSf/3R4nLeJKzR/696tc1SVHoAR47o0hV+srErbTi7JqDUYaooT4i9dX7jb6pMkpFSzOxR5UGxziaFsVWXinz81toMQGE593+5NHxzZX2+u4Iq7+i68/W6eZviAJbi56sBa2lyc6T40yFKV5IcfQ3hLotyGx2IoqsYWuv+WscX6osNdzyhmP0YTNrRusJ/yJIzRh4z1u/G2O8IPgkEJ//ky4Gk0FvqMECNoztO6IquhpmKDGKKvWZkQTs7a5a1ZesNNlk6b3jGtUrz6rraFK9Ac2GdbIqs3iZIVsv25hx7A=
  template:
    metadata:
      name: coder-admin-token
      namespace: coder
