---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: coder-workspaces
spec:
  encryptedData:
    .dockerconfigjson: AgCOI9ZFeWVQCdGu/IEDkYHtrMl+KDjjfUIbNX6qRiIqkgYpPw2KUkbH8OiYlPFUvW/1PLU9JanJpYi3s7GplY+ws1K4csP3tFdJrHyggfHMk3IOGYvemgj632HhCGlgWs7RaBM5+lzDdHGNoEe8TBBJO8YH267vfb3NPk9bV4nf49pMVyxCTShGQ6X+Ma5vItMN/HVWBozdHWQIcuDwwzynCxQgxUpZNIcrx8Zc8nuFyyq5wrR3NCB5vqe3iLnfauAK8wxQGXQdJht6r4dTYCXye/MbkK6weoO9xufMoyItBca69jf8v77m12odRWL/3f2JZwClGI1vh6xrgajCzPN12Q1jM3e/ulo5HgUnSFh+dGynVBI1BUSA5PSnlBJxvi7OGzaTQW7TNmp5CNrZQtW026QeOfK//QhqaygYVVMWVkz5jeABodebonVrffH+aKGeI7AK7i4+xhIVCNqjwdJ8/bW+HH/pyZSgUz53Qc4ghpVz5eCZWDxKT1mBh7Q/NxKhqtrJXnwjAEGpO4DaZP+KvaIuqxytolrhzGEUfMekrAVcxopKA29DtGR8PKwyNUk1Hx9+KEYCuoKaFBHPkrtYAY8IX7hgv02DnGiRjBYNVoLZ8fO1s8C81a3RyXmZOXfYBBMffSbo/BAfcG75ftBsa/I8RqiuzNWKz+PDpJ/UMXy4QA1OQRNwIdbQipPSlnH5M2BHFoOZFMICTbXqHpEc8ebts1DroVJnL3YaJ4a4ocHfDK1icOrkWpD3cg6qNXbkGs6EIBasqBn1rYNUCXi0DEziGclnHyWpype9+Bw7H3BE8FDM1VqeNEuYM0/hpPtiP3k4ji9gUlWtiUX85Gk9lwV7S4EEK4ZMs4FlBwzUvVbEtDYuTjm/eaFE3J2ljrC0OgvfgOwxVT/bbg/GpyVTSAFVyo91hj7PnUYc3DlY5KnTkEixZxGEofcNk1oINOPTv49pV98cdGEd77rm
  template:
    metadata:
      name: ghcr-pull
      namespace: coder-workspaces
    type: kubernetes.io/dockerconfigjson
