---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-oauth-client-secret
  namespace: openshift-config
spec:
  encryptedData:
    clientSecret: AgBkhaT6Ltx5LTuH9zoYFPlhPITvUJwa+LMkNR2x68ZPIRV3AzC071ZJGWc4G/sABWe8Tv9an7w+Z2LlS+b8iCOwd/6pIrLLynWPniiry7sTz9gNm3k3PWZ3mP3Un6f+2ExH6r8Q6jNZr19ByYmHKbMXp3z/UpfT9Pkh3G/s2j/fRhnkA5blKnv1ep+VviIA4Qgt2WNYY+HDBTMO5S+oVu9vlY/Omk8gbTk8LAimS1nkSH29myNKew+Ko166xkIX18keD/t67+OuCGlY07swV3pQRBXR8Mc1mZVX3Sk3/Vg1iYUqjxOFc0+UXnpKUjms1YNHpiiVYaflPj1ZnQr5IgSAHtHNVuK187hzWfVM0S9lonqjgv1PNM5pMLtNwUHeL09UaMRC7BNM0fI7zJM3lC4LrseT7bTnonv5D7drKduuVs7mdoNqui9Yq/JrkrFk2KESQyiHrR8GZzhAOKdJH+htLcixueCPWDrucsdeNHExQp8uyhJiJGx9qf7OtSWjdOUWvNrC26ZQyjxg+2vKhgYioMoUOmdCbqdae7lwxDhA5fvTayA6p7rrgxwslTdP4bddOGm56agQEE7weBWEclemFkci/bRlr34Gt7j1b7xu+dapSFZJ2MEU93LYQvhvz7ABgpYPUHRraGchyz2vjIqRFI9a1v5Mzo096Xmu7qkXMnjvU5X3zK3aP+zWn2YaZ07rJ+RJs8wEZy2yfx+SAEFcqWf8YMq8k5kaw76agYOyMy6/1iPetX6B
  template:
    metadata:
      name: github-oauth-client-secret
      namespace: openshift-config
