---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-group-sync-token
  namespace: group-sync-operator
spec:
  encryptedData:
    token: AgBovbWxfeDvozaDqcF86nBjDBi6gO72AHz4qan2qK+wqtX/1pzPHVoj3ku+v2OImlWC6iA7xqWWIM3f7WuhQ+BpGhUDsZchn2sYG+qiNeDe/iDF8gNEr+K/5T+/9Wj8N17C9KIHv/C/hUpqrwIsYyjlpsI7MyLdHvtb8/sfb58iP+jx66LEPRLZqinncWPVgYHud1rfvm/VV0UC/FLFTsDz07ehTOHjDPhIHKgzKUTyamrLK9zswlacew7FpCTZJqfb4V0UsUlbMEyqbIlxcsA2y8JuGlvYEeflNOGkTXUJVNLeu0IMeIQQG/3+Jh7AeESxHfwVqPQYkOhTLWxhG1bgYM6kIsbvtpNUIolgErsUR+E18QDJ+jD5yi0DKWwYTQF7239PaGDWzwGxNihZ1c4AV7vPAAoMA7xOMjj4fxFR6c+nTF0+6f1v3g1jVJY1tk8oXkfnrZtAxBOvM/J755ZXxoaZP9PkjEoNc+59eznyauwoI5xgVX9SwD4VlxVEzB/mCfNrftO3+yR7plzQNPTryfDV0ptkt8eBwCV5TYuK7Fri+pfOPj6wjGFQsfIUcXS1w/Ks0dZGEAiJLBKBQwlsH0wbnVajRiiAnM+HXJVwtOjOYRXUtdNwXAeQ+jcpvqNfKxbg1h1ZfCGr0/gtqs1n4Zu1eV8qMRPJTfMgjBjbT15ZkXXYsVuZqC9GcjbE3DVo34oL3/JGdoeJ0Jof5f5R1PNVhH3HHo+gPVdypinblN5Kv8D9M87c
  template:
    metadata:
      name: github-group-sync-token
      namespace: group-sync-operator
