---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-coder-external-auth
  namespace: coder
spec:
  encryptedData:
    client-id: AgAi9oXTRQmKsG7wbeQdDCIgt6Aa8Mfdqo/d2qKtiYv+a6vZAIl4UYbei9qW2sDYLpQnzwpz6opBDLwuNgN/UWFp4FpHJ/rUjRa2ps9a/7FpEONpAkZTRz5W4pjzLj23kPmK8ThKG2RzhM1rX8pYhl6CQitgz99QA/WQt5rtHvW0k9wdoT9pexzvTP04KXK3KKUeqXuOn8wMcU1emTkJoBYMqcgQR2zxCSPNTcE8wwygnZN/BEb8EdGLkZM5MRY2NY6GBXWtmgKqCjcftSV5VGE8HhPFIlfHLby4UeWMjzOMdUZY8WdOgRnwYemnWJVV5oXGhgrwZP8F/yPjWlayCV2AApwrXuqqbVXfwHjZzElFIpXMrLu27Wd0y9/m6iVG05Gxe7xW7aoWqG1Bd0C3Ccc3EuibowyP1fvlqVhE6P64FaNANvQe/j2j+TsDJIJKygaX41wXuMH8s98MuqaTk+AU9XXboceEzf+8ocTQjth4YphDw3EcCXxuC9LzmZUDhxP4R8aEiOB6A60ifwKosKfMAO7qrM4zCEQQxUCt0uRey0C7LFL+Xg2RJ8yRhXXiRCWaoKGCOrXYKFdMpeTbUkhm7kkolA6pQNXHTFkGzwOOfT6yWUYYCy2lJfMglJERVSS+uWPO1NjLaADs2V4kCPshBIK866VJtFBET4y/lwvf0btlXDcJbRVqZAu+28ziKy6NE5y3gfidARJoK4Wz/9qVHu4f3UIPzQZpusxfQxJBZeP35FCIxhHtbGEDWytOZ/qII0krzX5KbAAFw780MtIR
    client-secret: AgAx5ev+eZV1AbEdq75dFJ76kj2BhVSgBZPIDe+eYT/sVvUT8x2okRetz0vJhpVw86mDZAxxoY/W87YZ78iyBlJuzFyJdrhrnmEIgS/y38r62Khjq3aS7/4thHHOg38zEEzcD41T6ryZyIXTXirgAFgVH08q93nHFn/DupiXVMEMRYvDc78+1x5MtW9eo1gpD2kvUK+UgmBQYD7vd1tpiPEF1hwNrkubN4mJMYzd2qkQjZv6ayLaPRjUEW8GiacabpInRLJBX/DJ3OIMEfygvf6fgwfT12u3RomN8IH6dv7u8snai8hMT7V2a8Ow+tjgadVakICPZDWGlira/jNYR6gocBBsrqgbWYKreru6fbr9s3rTPRLWqf4uv8s/M4ruWP91/JhVY1oJuuk0IC26XDPXO4DwempZLP/zC7pdZlZ7rqgSgf2ec7U1X+E5JPLDHvRjeITbDRrEkr3DjRDHzAaB/1HxoP7+SI783MPyynmpwT472dF8maxMvqDv7Phbte5IeeEAOk/JVWzFKFKcroFY0OeTuOjEmoPUOLkIJAslBVnvqUpMvzDb4ZQAbDC/Lc9RkVXXrPV09eH20muU2WB+mFMB8K35U/Glz3NPKJ1HKC45PulLLOgQfRU5VGffkhi4iBvchOV38Sl2YowTw3cAvaybTldhqAEk97fjKhcUOkK7ym1b8A3tZISeKc45vusI0cI1EP9Ircls5WZPtikelER4KdazaR2SkJhU+OaaJNe4M3DE1d39fdA0l8DX2JZlLFHdJY9sp9ioQM1dntKD4fbtHKNG
  template:
    metadata:
      name: gitlab-coder-external-auth
      namespace: coder
    type: Opaque
