---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-bridge-pat
  namespace: coder
spec:
  encryptedData:
    token: AgBWtqLvzLHRCYrQagHJVaXAPCTc34lQFWP1Sv5Hla4S+cxU9E619mETYmTTWV6iDiCbmKkjL1stU3I9hqRjzN6QKZE75oX4drdRPyU1f0mIf7XitUmKfZJZHgWtB4BvyoWGHIMxzGgLKjYxF/2S4ud/n7PznujsH6fuRlE8afFffIaZgkhlo7tRTjotf/Ego9ksX0ZtBVI/rCSvniFvZWu3LsANw895uDy/ICHZIJEiSLs1KhwuNxgsHlyPSpV5dojOZGbh+IoOA2sLtUKM9cN4+Eq4r1jif790Owo1KvUQhoxyNA/7f9/QCmQaejSzPVShev02tcgcZlDBD9bBPq/AWr+bdU9Yx81Ic149TesC1OgGr+gDvuQp5ChjSA6xffzpjy6NqV/ejWorr+Mb+ODUAss2zEiLOcYil/fZ4eF2S1gEs1FiSWdW2gRvqze+4HWOaOEQ8Zn/WCmLIv6mBLCYVQmhOoLaQJZexmVk+lad0nt7O7q3EvH9U4NN0X7GzFLJy+NemNaBaiOrIeg5dROqoWayPCOg028sfu1LucKswmZaSNyKDUtXEaGSoO4WL/IWC6x9ptucD3IEfSk9WE6/bqJHOzMZLaRfaFT2L4APYIq6Qlo4wNOES3VHPkSz9x1EvTsPBSQhv3g5L3DIEJbdmrta6nSeB+ZZXcTtPcakMtcAL91j1wJ9NN6mZwga//rMQON31ClIvoiwU1v3unBVmrt4u3zCy+rKSfbcHYXM44t3jheCQVmoo6axd2LqlXlLBP0=
  template:
    metadata:
      name: gitlab-bridge-pat
      namespace: coder
