---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-grafana-oidc-secret
  namespace: coder-observability
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgBiwoQWzfWD3/hUJbH/UBHlJuu61lTav2FR1V6ufSIjzme6ozlwn+1wzgj/0b93pSKrWGxnEnqsmhh33LYwyiAYhw14LHmcDBTtTHrFoknh+a/rlINaWcDlvURGuxuzDNahqFXSaqmrrmYw4ZKusWL9oN5S588HjQZL024OVtSEgKQQEQ7KHFWeoTJZQTeszqqkjnEcE4d8LVS/pV0jKGIGIVh4s63u+TNntjvIMwWmyESdWcQJEBOM93dtiH4Xz4rkS2pxKmHgEphOqFYwbxhz/Hv7bEDWYYhh98X3r7pKx1ckQXUjrIRq8ySotD7YYxiIue/lJFq2xsBtl/YkjO3JOMZAM+S/V0J95ZyB0j5bNVTr0ekYfuynAXWU2sbRcmHeg314GZ+QaDf9661uXFuDkd4DtTiB4eMkB3vOSrWdISOElG6B1tmNWeZMbaDiTA5Nhp65RImDJmcKrq6eO8b7NqsKsCHSrZLQZYLk160eyWhY/Sl/Nmxg12zKinHQhtqTGnG8HHTVFG9NT8q8GghoAbTdwQ1ia1aO45uW2PrgJcrkKZpvSf6HlcUQTe4ggfgkLZ5zbiU8T7q5teB/BiwtuRaI9PC4KhwN+PebBFLkLuQQ7Hns0bYP45tWnqw62e8GFxS4Ac9ZEOj5yP3ph5fY1QBEsmv8OEw3/JM0OOB0kdYWg+OufnzG0xRNy25gSea+EZNjc5XiSR3/znArZNKkn8wF9fz14uxfqgLlwbcm
  template:
    metadata:
      name: keycloak-grafana-oidc-secret
      namespace: coder-observability
