---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-openshift-oidc-secret
  namespace: openshift-config
spec:
  encryptedData:
    clientSecret: AgAqw/sYh49tPUR+W1krDnj/tct6yNxJI+fdCeOO5wnF3L2qEv5NkwztkOml25wzif1boug9nZqcWp+ts5Ce+lypQLqMWgmOMARlPWZjjJAPLTQy4ZGCoHEPDwXTnXhafwHryikjPIygo8MC2gEtUR+CwjpFoEWFpVlODf+qfRDxR4scaXGuJIyi7v5VQkWKrzTyeNPAtUBEOQft9J59ijZkciPVno0szy5BSZB9TkTb3Bw7mTWUfQFfzJKRHLkqqd5/AMLwYx2qspJMWyTOTosVgdI1N08+OzxTL5Q7TjPeibU3zXK8OTUDWr2XcR1LtkN0NYtqnlz2Rpl+Iv8RucZXPFMcehpKojt+ca9s2DrJ8JT2eRVBlqRvE39IDwRb7RshlIu1um5Rjs/GvETps4qH5OwcZISJ2E6sxFvF2vVfe8Z0dSJ90aOPvlSTfOlXBzebi7CL5wJ1T9S8/GJeFx6nra+8MJrpBhp9QP9Dp1Vm6znikVVGK/O53zNsKoyeYSeKzef+NNseogvtfR+JEyf4HXQR/L3NwB/unLmr1C6p+EQDPqMu0vDfQxgOPTtUCzar8lW9u7YbFOyeIbkDigXzijyunyWqrlYlrTEWYv6nCbp1cLBvXnVDRnuORa6MUs2V20TyKGtUePg+LFHj84TdrFQg8iMGOQjArGkO+23UlDVcPPTnZomGlGFIbKSjXaDoucBxDMDPEUo7irF/VxglKzlVX7Su/urzKL7oA5LDXw4=
  template:
    metadata:
      name: keycloak-openshift-oidc-secret
      namespace: openshift-config
