---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret-postgres
  namespace: coder-observability
spec:
  encryptedData:
    PGPASSWORD: AgChvcv8rv2eAV1Ts8jT6nxcwW16xaao5cn+EVNsYjUpq70Tti2MRjnS/IiE6ITSpyYeeUK/KYL+d+3xWy77Q/iZr+oqnwp/B91X80Fg/NdALhpdb/lQ0k4DDTbdqkGYhib2Ei4ANkJOkCN5u0x5ziWVKnVJ41Fl/l1IuRsjU6Q4Of6gfklnBVRioYWjpygwP3RZP4I4B7Xh0xsi8TdfeAtuKjQ8356gvSWsH0asci1d/3MecAYQbn1ReJ+yti1H1lNqBKTiMJzJr9JX7zZiFHCEnboVBj9WJhHxNcpERWTXmjuCINmH68+VNHOEKUtuMyXtNYNFSFPy//Csz0eOy7rVZzhFqHGv0q4UFshJZrXIXENnI7VsrbSaKmCLP6s/nqH33/GHCWtkLVJbeGEAbkq0tH//BLSNWiIKklney2+uMZwAMD70/TsXRAJ5vvN0h+pRa8Ai6pY925FzoPy5le69uk4FICeOqCJse6rMrehLmfprfaeF/MM17te0ZBy58WN7GbriG8lt8VBtvxdJMGcTsY3tD/sQ2n1fdn3DUPvrta/MXa/tvwGQ7JTWHThj7ZZHNvMP148ZWVb6VmjStbbIqAbcZ2wUQRrs29kz3xVQy33MNxzQeU+8hLOeYSuYC3ojaDCiGnRprrEPTUv1VaeKOO2gFiURzXHvb/cblP/YYwOn/zhqH7n/OvcOMOiOSnT92sYZUmwc+IRRKEGbG6yh4SRLKIadz+Bo9zqRpXroeLMBwKqu0HCBifr3UZz4yKKDblWjZMEPC0eLUAVLlja8
  template:
    metadata:
      name: secret-postgres
      namespace: coder-observability
