apiVersion: v1
kind: ConfigMap
metadata:
  name: infinity-datasource
  namespace: coder-observability
  labels:
    grafana_datasource: "1"
data:
  infinity.yaml: |
    apiVersion: 1
    datasources:
      - name: litellm-pricing-data
        type: yesoreyeram-infinity-datasource
        uid: litellm-pricing-data
        access: proxy
        isDefault: false
        editable: false
        jsonData:
          allowedHosts:
            - https://raw.githubusercontent.com
